### PR TITLE
WIP: Improved structure

### PR DESCRIPTION
**Pull request by NOhs**
This is a suggestion of a structure that has the following advantages:
- Using a more OO approach, a lot of if-statements vanish as we now have lists of different classes [executables, header-only libraries, shared libraries, static libraries] that all know what to do when they are asked to compile/link. This structure is also easily extendable with new types without the need to change one giant function in a lot of places
- Following this OO approach the assembly of all targets was redesigned so that a target can assemble itself. For this, the targets mentioned in the toml file are first put into a dependency graph and topologically sorted. After this they can be easily constructed serially
- Output is now done via logging, allowing easy filtering of output dependent on user input
- Dialect check is done without temporary files
- Using the pathlib2 library instead of concatenating strings
- Adapted some naming to more standardish naming schemes in python (WIP)
- Using python unittests for the testing
- Disentangled the build function from the argument parsing

Still missing:
- Some features still need to be copied in like external projects
- Using map_async for compile
- Parallel linking stage
- Better output formatting (needs discussion)
- Making all test pass
- Adding more tests (should probably be a separate pull request)
- Make CI use the new test structure
- More code clean-up, some code still seems messy and unnecessarily complex

### CODE REVIEW

**Comment by GPMueller** [comment]
`pbr` seems to make problems on Windows. Emptying the setup.cfg and instead filling the setup.py with
```Python
#!/usr/bin/env python

import setuptools

setuptools.setup(
    setup_requires=['pbr>=3.1.1'],
    name = "clang-build",
    author = "Trick-17",
    summary = "Easy build tool for C++ projects focussing on simplicity",
    license = "MIT",
    url = "https://github.com/Trick-17/clang-build",
    long_description=open('README.md').read(),
    keywords = "clang, build",
    package_dir={'': 'clang_build'},
    # pbr=True,
    entry_points={
        'console_scripts': [
            'clang-build = clang_build.clang_build:main',
        ],
    },)
```
Resolves the problem that no `.exe` is created.

See also https://github.com/PyCQA/pydocstyle/issues/73 and https://github.com/Nurdok/pydocstyle/blob/b7e60d43676f1a636353371f8b34e8b7462a219a/setup.py

**Comment by GPMueller** [comment]
For generating a unique version tag, see for example https://github.com/spirit-code/spirit/tree/master/core/python
```Python
def get_git_commit_datetime():
    try:
        commit_hash = subprocess.check_output("git rev-parse HEAD", shell=True, stderr=subprocess.STDOUT).decode("utf-8").strip()
        commit_datetime = subprocess.check_output("git show -s --format=%ci "+commit_hash, shell=True, stderr=subprocess.STDOUT).decode("utf-8").strip()
        print(commit_datetime)
        datetime_object = datetime.datetime.strptime(commit_datetime, '%Y-%m-%d %H:%M:%S +%f')
        print("{:%Y%m%d%H%M%S}".format(datetime_object))
        return "{:%Y%m%d%H%M%S}".format(datetime_object)
    except subprocess.CalledProcessError as cpe:
        print(cpe.output)
        return "00000000000000"
...
    # If the environment variable SPIRIT_VERSION_SUFFIX is defined,
    # it is appended to the package version number.
    version_suffix = ""
    add_version_suffix = os.environ.get("SPIRIT_ADD_VERSION_SUFFIX", "")
    if add_version_suffix.lower() in ("yes", "true", "t", "1"):
        timepoint_string = get_git_commit_datetime()
        if timepoint_string == "00000000000000":
            timepoint_string = "{:%Y%m%d%H%M}".format(datetime.datetime.now())
        version_suffix = ".dev"+timepoint_string
        print("setup.py: package version suffix = ", version_suffix)
```
The environment variable is used to optionally add a `.dev<timepoint>` string, while otherwise the base version of the package is used. That means the version is set manually and not read from git tags.

The idea is to mainly work on a `develop` branch and only merge releases (i.e. a new version number) to the master branch, where the `.dev` tag would not be added by the CI.

**Comment by NOhs** [comment]
There is also https://github.com/pyfidelity/setuptools-git-version, but it doesn't seem to be too actively maintained and is lacking some basics (like working on a git repository without tags).

Maybe we could implement our own version based on how pbr and the above mentioned repositories work. Shouldn't take too long.

**Comment by NOhs** [comment]
Ok, let's maybe not abandon pbr right now. It seems to be an issue with the latest 4.0 Version. I downgraded to pbr 3.1.1 and it works again. I suggest this solution for now.

See also: https://bugs.launchpad.net/pbr/+bug/1761134

**Pull request merged**
